version: '3.8'
services:
  backend_my_readings:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_my_readings
    entrypoint: sh -c "yarn install && yarn start:dev"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - my_readings_networks
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
      - nginx
    links:
      - mongodb
    ports:
      - ${PORT}:${PORT}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGODB_URI: ${MONGODB_URI}
    volumes:
      - data:/data/db
    ports:
      - '27017:27017'
    networks:
      - my_readings_networks

  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:8080
    networks:
      - my_readings_networks

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
      - REDIS_HOST=localhost
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    hostname: ${REDIS_HOST}
    networks:
      - my_readings_networks
    volumes:
      - cache:/data

volumes:
  data:
  cache:

networks:
  my_readings_networks:
