version: '3.8'
services:
  nodeserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodeserver
    entrypoint: sh -c "yarn install && yarn start:dev"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_PORT: ${MONGODB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      NGINX_PORT: ${NGINX_PORT}
    networks:
      - nodeserver_network
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
    ports:
      - ${PORT}:${PORT}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGODB_URI: ${MONGODB_URI}
    volumes:
      - data:/data/db
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - nodeserver_network

  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:${NGINX_PORT}
    links:
      - nodeserver
    networks:
      - nodeserver_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
      - REDIS_HOST=localhost
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    hostname: ${REDIS_HOST}
    networks:
      - nodeserver_network
    volumes:
      - cache:/data

volumes:
  data:
  cache:

networks:
  nodeserver_network:
